package View;


import Model.BaoCaoTienDo;
import Model.DangKyBienSoanGiaoTrinh;
import Model.TacGia;
import Model.FileController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class BaoCaoTienDoView extends javax.swing.JFrame {

    /**
     * Creates new form BaoCaoTienDo
     */
    public BaoCaoTienDoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formBaoCaoTienDo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        XacNhanBaoCao = new javax.swing.JButton();
        HuyBaoCao = new javax.swing.JButton();
        txtMaGT = new javax.swing.JTextField();
        txtTienDo = new javax.swing.JTextField();
        HuyBienSoan = new javax.swing.JButton();
        XinGiaHan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("BÁO CÁO TIẾN ĐỘ GIÁO TRÌNH");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Mã giáo trình :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Tiến độ :");

        XacNhanBaoCao.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        XacNhanBaoCao.setText("Xác nhận");
        XacNhanBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XacNhanBaoCaoActionPerformed(evt);
            }
        });

        HuyBaoCao.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        HuyBaoCao.setText("Huỷ ");
        HuyBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyBaoCaoActionPerformed(evt);
            }
        });

        txtMaGT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMaGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaGTActionPerformed(evt);
            }
        });

        txtTienDo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTienDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienDoActionPerformed(evt);
            }
        });

        HuyBienSoan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        HuyBienSoan.setText("Hủy biên soạn");
        HuyBienSoan.setActionCommand("X");
        HuyBienSoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyBienSoanActionPerformed(evt);
            }
        });

        XinGiaHan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        XinGiaHan.setText("Xin gia hạn");
        XinGiaHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XinGiaHanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formBaoCaoTienDoLayout = new javax.swing.GroupLayout(formBaoCaoTienDo);
        formBaoCaoTienDo.setLayout(formBaoCaoTienDoLayout);
        formBaoCaoTienDoLayout.setHorizontalGroup(
            formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1))
                    .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaGT, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(txtTienDo)))
                    .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(XacNhanBaoCao)
                        .addGap(18, 18, 18)
                        .addComponent(HuyBienSoan, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(XinGiaHan)
                        .addGap(22, 22, 22)
                        .addComponent(HuyBaoCao)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        formBaoCaoTienDoLayout.setVerticalGroup(
            formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtMaGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XacNhanBaoCao)
                    .addComponent(HuyBaoCao)
                    .addComponent(HuyBienSoan)
                    .addComponent(XinGiaHan))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(formBaoCaoTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(formBaoCaoTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HuyBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyBaoCaoActionPerformed
        // TODO add your handling code here:
        menuChinh f = new menuChinh();
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        f.setLocationRelativeTo(null);
        f.setResizable(false);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HuyBaoCaoActionPerformed

    private void XacNhanBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XacNhanBaoCaoActionPerformed
        try {
            if (txtMaGT.getText().equals("")) {
                txtMaGT.requestFocus();
                throw new Exception("Nhập mã giáo trình!");
            }
            if (txtTienDo.getText().equals("")) {
                txtTienDo.requestFocus();
                throw new Exception("Nhập tiến độ!");
            }
            JOptionPane.showMessageDialog(this, "Bạn đã báo cáo thành công!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
// TODO add your handling code here:
        String maGT = txtMaGT.getText();
        int tienDo = Integer.parseInt(txtTienDo.getText());
        BaoCaoTienDo bctd = new BaoCaoTienDo();
        FileController fileController = new FileController();
        List<DangKyBienSoanGiaoTrinh> dkbss = ReadFileDK("TienDo.DAT");
        bctd.XacNhanTienDo(maGT, tienDo,dkbss);
        WriteFileTĐ(dkbss, "TienDo.DAT");
    }//GEN-LAST:event_XacNhanBaoCaoActionPerformed

    private void txtTienDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienDoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienDoActionPerformed

    private void txtMaGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGTActionPerformed

    private void HuyBienSoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyBienSoanActionPerformed
        // TODO add your handling code here:
        HuyBienSoan f = new HuyBienSoan();
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        f.setLocationRelativeTo(null);
        f.setResizable(false);
        f.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_HuyBienSoanActionPerformed

    private void XinGiaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XinGiaHanActionPerformed
        // TODO add your handling code here:
        XinGiaHanView f = new XinGiaHanView();
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        f.setLocationRelativeTo(null);
        f.setResizable(false);
        f.setVisible(true);
        this.dispose();
        
        String maGT = txtMaGT.getText();

        BaoCaoTienDo bctd = new BaoCaoTienDo();
        FileController fileController = new FileController();
        List<DangKyBienSoanGiaoTrinh> dkbss = ReadFileDK("TienDo.DAT");
        WriteFileTĐ(dkbss, "TienDo.DAT");
        

    }//GEN-LAST:event_XinGiaHanActionPerformed


    public List<DangKyBienSoanGiaoTrinh> ReadFileDK(String fileName1) {
        FileController fileController = new FileController();
        List<DangKyBienSoanGiaoTrinh> dkbss = new ArrayList<>();
        fileController.OpenFileToRead(fileName1);
        while (fileController.getScanner().hasNext()) {
            String infor = fileController.getScanner().nextLine();
            String[] data = infor.split("\\|");
            String[] data2 = data[data.length - 2].split("\\*");
            List<TacGia> tgs = new ArrayList<>();
            for (int i = 0; i <= data2.length / 2; i += 2) {
                String ten = data2[i+1];
                String vaiTro = data2[i + 2];
                tgs.add(new TacGia(ten, vaiTro));
            }
            DangKyBienSoanGiaoTrinh a = new DangKyBienSoanGiaoTrinh(data[1], tgs, data[2], data[3]);
            a.setTienDo(Integer.parseInt(data[data.length-1]));
            a.setMaGT(data[0]);
            dkbss.add(a);
        }
        fileController.CloseFileAfterRead();
        return dkbss;
    }
    
    
    private void WriteFileTĐ(List<DangKyBienSoanGiaoTrinh> dkbss,String fileName) {
        FileController fileController = new FileController();
        fileController.OpenFileToWrite(fileName,false);
        for (DangKyBienSoanGiaoTrinh dkb : dkbss) {
                String str = "";
                str += dkb.getMaGT() + "|" + dkb.getTenGT() + "|" + dkb.getNoiDung() + "|" + dkb.getThoiGianHT() + "|" + dkb.getThoiGianDK() + "|";
                for (TacGia tacGia : dkb.getTacGias()) {
                    String tmp = "*" + tacGia.getTenTacGia() + "*" + tacGia.getVaiTro();
                    str += tmp; 
                }
                str+=  "|" + dkb.getTienDo();
            fileController.getPrintWriter().println(str);
        }
        fileController.CloseFileAfterWrite();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoCaoTienDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoCaoTienDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoCaoTienDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoCaoTienDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaoCaoTienDoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HuyBaoCao;
    private javax.swing.JButton HuyBienSoan;
    private javax.swing.JButton XacNhanBaoCao;
    private javax.swing.JButton XinGiaHan;
    private javax.swing.JPanel formBaoCaoTienDo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtMaGT;
    private javax.swing.JTextField txtTienDo;
    // End of variables declaration//GEN-END:variables
}
