package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author LENOVO0
 */
import Model.DangKyBienSoanGiaoTrinh;
import Model.TacGia;
import java.util.ArrayList;
import java.util.List;
import Model.FileController;
import javax.swing.JOptionPane;

public class DangKiBienSoan extends javax.swing.JFrame {

    /**
     * Creates new form DangKiBienSoan
     */
    public DangKiBienSoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formDangKy = new javax.swing.JPanel();
        ThoatDangKy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        XacNhanDangKy = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextArea();
        txtTenGT = new javax.swing.JTextField();
        txtSoTG = new javax.swing.JTextField();
        txtThoiGian = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ThoatDangKy.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ThoatDangKy.setText("Thoát");
        ThoatDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatDangKyActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Tên giáo trình: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Số tác giả :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Thời gian hoàn thành :");

        XacNhanDangKy.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        XacNhanDangKy.setText("Xác nhận");
        XacNhanDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XacNhanDangKyActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setText("ĐĂNG KÝ BIÊN SOẠN THÔNG TIN GIÁO TRÌNH");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Nội dung : ");

        txtNoiDung.setColumns(20);
        txtNoiDung.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNoiDung.setRows(5);
        jScrollPane1.setViewportView(txtNoiDung);

        txtTenGT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtSoTG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtThoiGian.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout formDangKyLayout = new javax.swing.GroupLayout(formDangKy);
        formDangKy.setLayout(formDangKyLayout);
        formDangKyLayout.setHorizontalGroup(
            formDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formDangKyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(130, 130, 130))
            .addGroup(formDangKyLayout.createSequentialGroup()
                .addGroup(formDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formDangKyLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(formDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(46, 46, 46)
                        .addGroup(formDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTenGT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(txtSoTG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThoiGian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(formDangKyLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(XacNhanDangKy)
                        .addGap(91, 91, 91)
                        .addComponent(ThoatDangKy)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        formDangKyLayout.setVerticalGroup(
            formDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDangKyLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addGroup(formDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtTenGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(formDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtSoTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(formDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(formDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(formDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XacNhanDangKy)
                    .addComponent(ThoatDangKy))
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(formDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(formDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThoatDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatDangKyActionPerformed
        // TODO add your handling code here:
        menuChinh f = new menuChinh();
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        f.setLocationRelativeTo(null);
        f.setResizable(false);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ThoatDangKyActionPerformed

    private void XacNhanDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XacNhanDangKyActionPerformed
        try {
            
            if (txtTenGT.getText().equals("")) {
                txtTenGT.requestFocus();
                throw new Exception("Nhập tên giáo trình!");
            }
            if(txtSoTG.getText().equals("")){
                txtSoTG.requestFocus();
                throw new Exception("Nhập số tác giả!");
            }
            if (txtThoiGian.getText().equals("")) {
                txtThoiGian.requestFocus();
                throw new Exception("Nhập thời gian hoàn thành!");
            }
            if (txtNoiDung.getText().equals("")) {
                txtNoiDung.requestFocus();
                throw new Exception("Nhập nội dung!");
            }

        
            JOptionPane.showMessageDialog(this, "Bạn đã đăng ký thành công!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        
        List<DangKyBienSoanGiaoTrinh> dkss = ReadFileDK("DsDangKy.DAT");
        String tenGT = txtTenGT.getText();
        int n = Integer.parseInt(txtSoTG.getText());
        List<TacGia> tgs = new ArrayList<>();
        for (int i = 0; i < n; i++) {
            TacGia tg = new TacGia();
            tg.Nhap();
            tgs.add(tg);
        }
        String thoiGianHoanThanh = txtThoiGian.getText();
        String noiDung = txtNoiDung.getText();
        DangKyBienSoanGiaoTrinh a = new DangKyBienSoanGiaoTrinh(tenGT, tgs, noiDung, thoiGianHoanThanh);
        a.setMaGT("GT"+(dkss.size()+1));
        dkss.add(a);
        WritetoFile("DsDangKy.DAT",dkss);
        WriteFileTĐ(dkss, "TienDo.DAT");
    }//GEN-LAST:event_XacNhanDangKyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKiBienSoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKiBienSoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKiBienSoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKiBienSoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKiBienSoan().setVisible(true);
            }
        });
    }

    public List<DangKyBienSoanGiaoTrinh> ReadFileDK(String fileName1) {
        FileController fileController = new FileController();
        fileController.OpenFileToRead(fileName1);
        List<DangKyBienSoanGiaoTrinh> dkbss = new ArrayList<>();
        while (fileController.getScanner().hasNext()) {
            String infor = fileController.getScanner().nextLine();
            String[] data = infor.split("\\|");
            String[] data2 = data[data.length - 1].split("\\*");
            List<TacGia> tgs = new ArrayList<>();
            for (int i = 0; i <= data2.length / 2; i += 2) {
                String ten = data2[i + 1];
                String vaiTro = data2[i + 2];
                tgs.add(new TacGia(ten, vaiTro));
            }
            DangKyBienSoanGiaoTrinh a = new DangKyBienSoanGiaoTrinh(data[1], tgs, data[2], data[3]);
            a.setMaGT(data[0]);
            dkbss.add(a);
        }
        fileController.CloseFileAfterRead();
        return dkbss;
    }

    public void WritetoFile(String fileName, List<DangKyBienSoanGiaoTrinh> dks) {
        FileController fileController = new FileController();
        fileController.OpenFileToWrite(fileName, false);
        for (DangKyBienSoanGiaoTrinh dk : dks) {
            String str = "";
            str += dk.getMaGT() + "|" + dk.getTenGT() + "|" + dk.getNoiDung() + "|" + dk.getThoiGianHT() + "|" + dk.getThoiGianDK() + "|";
            for (TacGia tacGia : dk.getTacGias()) {
                String tmp = "*" + tacGia.getTenTacGia() + "*" + tacGia.getVaiTro();
                str += tmp;
            }
            fileController.getPrintWriter().println(str);
       
        }
        fileController.CloseFileAfterWrite();
    }
    
    private void WriteFileTĐ(List<DangKyBienSoanGiaoTrinh> dkbss,String fileName) {
        FileController fileController = new FileController();
        fileController.OpenFileToWrite(fileName,false);
        for (DangKyBienSoanGiaoTrinh dkb : dkbss) {
                String str = "";
                str += dkb.getMaGT() + "|" + dkb.getTenGT() + "|" + dkb.getNoiDung() + "|" + dkb.getThoiGianHT() + "|" + dkb.getThoiGianDK() + "|";
                for (TacGia tacGia : dkb.getTacGias()) {
                    String tmp = "*" + tacGia.getTenTacGia() + "*" + tacGia.getVaiTro();
                    str += tmp; 
                }
                str+=  "|" + dkb.getTienDo();
            fileController.getPrintWriter().println(str);
        }
        fileController.CloseFileAfterWrite();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ThoatDangKy;
    private javax.swing.JButton XacNhanDangKy;
    private javax.swing.JPanel formDangKy;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtNoiDung;
    private javax.swing.JTextField txtSoTG;
    private javax.swing.JTextField txtTenGT;
    private javax.swing.JTextField txtThoiGian;
    // End of variables declaration//GEN-END:variables
}
