/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.BaoCaoTienDo;
import Model.DangKyBienSoanGiaoTrinh;
import Model.FileController;
import Model.TacGia;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class HuyBienSoan extends javax.swing.JFrame {

    /**
     * Creates new form HuyBienSoan
     */
    public HuyBienSoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formBaoCaoTienDo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HuyBaoCao = new javax.swing.JButton();
        txtMaGT = new javax.swing.JTextField();
        HuyBienSoan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("HỦY BIÊN SOẠN GIÁO TRÌNH");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Mã giáo trình : ");

        HuyBaoCao.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        HuyBaoCao.setText("Huỷ ");
        HuyBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyBaoCaoActionPerformed(evt);
            }
        });

        txtMaGT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMaGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaGTActionPerformed(evt);
            }
        });

        HuyBienSoan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        HuyBienSoan.setText("Xác nhận");
        HuyBienSoan.setActionCommand("X");
        HuyBienSoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyBienSoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formBaoCaoTienDoLayout = new javax.swing.GroupLayout(formBaoCaoTienDo);
        formBaoCaoTienDo.setLayout(formBaoCaoTienDoLayout);
        formBaoCaoTienDoLayout.setHorizontalGroup(
            formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(HuyBienSoan, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(HuyBaoCao)
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaGT, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        formBaoCaoTienDoLayout.setVerticalGroup(
            formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HuyBienSoan)
                    .addComponent(HuyBaoCao))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(formBaoCaoTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(formBaoCaoTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HuyBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyBaoCaoActionPerformed
        // TODO add your handling code here:
        menuChinh f = new menuChinh();
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        f.setLocationRelativeTo(null);
        f.setResizable(false);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HuyBaoCaoActionPerformed

    private void txtMaGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGTActionPerformed

    private void HuyBienSoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyBienSoanActionPerformed
        try {
            if (txtMaGT.getText().equals("")) {
                txtMaGT.requestFocus();
                throw new Exception("Nhập mã giáo trình!");
            }
            
            JOptionPane.showMessageDialog(this, "Bạn đã hủy biên soạn thành công!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        }

        menuChinh f = new menuChinh();
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        f.setLocationRelativeTo(null);
        f.setResizable(false);
        f.setVisible(true);
        this.dispose();
        String maGT = txtMaGT.getText();
        BaoCaoTienDo bctd = new BaoCaoTienDo();
        FileController fileController = new FileController();
        List<DangKyBienSoanGiaoTrinh> dkbss = ReadFileDK("TienDo.DAT");
        bctd.XoaTienDo(maGT,dkbss);
        WriteFileTĐ(dkbss, "TienDo.DAT");
    }//GEN-LAST:event_HuyBienSoanActionPerformed
    public List<DangKyBienSoanGiaoTrinh> ReadFileDK(String fileName1) {
        FileController fileController = new FileController();
        List<DangKyBienSoanGiaoTrinh> dkbss = new ArrayList<>();
        fileController.OpenFileToRead(fileName1);
        while (fileController.getScanner().hasNext()) {
            String infor = fileController.getScanner().nextLine();
            String[] data = infor.split("\\|");
            String[] data2 = data[data.length - 2].split("\\*");
            List<TacGia> tgs = new ArrayList<>();
            for (int i = 0; i <= data2.length / 2; i += 2) {
                String ten = data2[i+1];
                String vaiTro = data2[i + 2];
                tgs.add(new TacGia(ten, vaiTro));
            }
            DangKyBienSoanGiaoTrinh a = new DangKyBienSoanGiaoTrinh(data[1], tgs, data[2], data[3]);
            a.setTienDo(Integer.parseInt(data[data.length-1]));
            a.setMaGT(data[0]);
            dkbss.add(a);
        }
        
        fileController.CloseFileAfterRead();
        return dkbss;
    }
    
    
    private void WriteFileTĐ(List<DangKyBienSoanGiaoTrinh> dkbss,String fileName) {
        FileController fileController = new FileController();
        fileController.OpenFileToWrite(fileName,false);
        for (DangKyBienSoanGiaoTrinh dkb : dkbss) {
                String str = "";
                str += dkb.getMaGT() + "|" + dkb.getTenGT() + "|" + dkb.getNoiDung() + "|" + dkb.getThoiGianHT() + "|" + dkb.getThoiGianDK() + "|";
                for (TacGia tacGia : dkb.getTacGias()) {
                    String tmp = "*" + tacGia.getTenTacGia() + "*" + tacGia.getVaiTro();
                    str += tmp; 
                }
                str+=  "|" + dkb.getTienDo();
            fileController.getPrintWriter().println(str);
        }
        fileController.CloseFileAfterWrite();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HuyBienSoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HuyBienSoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HuyBienSoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HuyBienSoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HuyBienSoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HuyBaoCao;
    private javax.swing.JButton HuyBienSoan;
    private javax.swing.JPanel formBaoCaoTienDo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtMaGT;
    // End of variables declaration//GEN-END:variables
}
