/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.BaoCaoTienDo;
import Model.DangKyBienSoanGiaoTrinh;
import Model.FileController;
import Model.TacGia;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Anh Duc
 */
public class XinGiaHanView extends javax.swing.JFrame {

    /**
     * Creates new form XinGiaHanView
     */
    public XinGiaHanView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formBaoCaoTienDo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HuyBaoCao = new javax.swing.JButton();
        txtMaGT = new javax.swing.JTextField();
        XinGiaHan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtGiaHan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("BÁO CÁO TIẾN ĐỘ GIÁO TRÌNH");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Mã giáo trình :");

        HuyBaoCao.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        HuyBaoCao.setText("Huỷ");
        HuyBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyBaoCaoActionPerformed(evt);
            }
        });

        txtMaGT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMaGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaGTActionPerformed(evt);
            }
        });

        XinGiaHan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        XinGiaHan.setText("Xin gia hạn");
        XinGiaHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XinGiaHanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Ngày gia hạn :");

        txtGiaHan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtGiaHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaHanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formBaoCaoTienDoLayout = new javax.swing.GroupLayout(formBaoCaoTienDo);
        formBaoCaoTienDo.setLayout(formBaoCaoTienDoLayout);
        formBaoCaoTienDoLayout.setHorizontalGroup(
            formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                                .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(58, 58, 58)
                                .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaGT, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                                    .addComponent(txtGiaHan)))
                            .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                                .addComponent(XinGiaHan)
                                .addGap(84, 84, 84)
                                .addComponent(HuyBaoCao)
                                .addGap(111, 111, 111))))
                    .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        formBaoCaoTienDoLayout.setVerticalGroup(
            formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBaoCaoTienDoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGiaHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(formBaoCaoTienDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HuyBaoCao)
                    .addComponent(XinGiaHan))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(formBaoCaoTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(formBaoCaoTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGiaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaHanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaHanActionPerformed

    private void XinGiaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XinGiaHanActionPerformed
        // TODO add your handling code here:

        try {

            if (txtMaGT.getText().equals("")) {
                txtMaGT.requestFocus();
                throw new Exception("Nhập mã giáo trình!");
            }

            if (txtGiaHan.getText().equals("")) {
                txtGiaHan.requestFocus();
                throw new Exception("Nhập ngày gia hạn!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        String maGT = txtMaGT.getText();
        String giaHan = txtGiaHan.getText();
        BaoCaoTienDo bctd = new BaoCaoTienDo();
        FileController fileController = new FileController();
        List<DangKyBienSoanGiaoTrinh> dkbss = ReadFileDK("TienDo.DAT");
        for (DangKyBienSoanGiaoTrinh dkbs : dkbss) {
            if (dkbs.getMaGT().compareToIgnoreCase(maGT) == 0) {
                JOptionPane.showMessageDialog(this, "Bạn đã xin gia hạn thành công!", "Thao tác thành công!", JOptionPane.INFORMATION_MESSAGE);
                bctd.XinGH(maGT, giaHan, dkbss);
                WriteFileTĐ(dkbss, "TienDo.DAT");
            }
        }
    }//GEN-LAST:event_XinGiaHanActionPerformed

    private void txtMaGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGTActionPerformed

    private void HuyBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyBaoCaoActionPerformed
        // TODO add your handling code here:
        BaoCaoTienDoView f = new BaoCaoTienDoView();
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        f.setLocationRelativeTo(null);
        f.setResizable(false);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HuyBaoCaoActionPerformed

    public List<DangKyBienSoanGiaoTrinh> ReadFileDK(String fileName1) {
        FileController fileController = new FileController();
        List<DangKyBienSoanGiaoTrinh> dkbss = new ArrayList<>();
        fileController.OpenFileToRead(fileName1);
        while (fileController.getScanner().hasNext()) {
            String infor = fileController.getScanner().nextLine();
            String[] data = infor.split("\\|");
            String[] data2 = data[data.length - 2].split("\\*");
            List<TacGia> tgs = new ArrayList<>();
            for (int i = 0; i <= data2.length / 2; i += 2) {
                String ten = data2[i + 1];
                String vaiTro = data2[i + 2];
                tgs.add(new TacGia(ten, vaiTro));
            }
            DangKyBienSoanGiaoTrinh a = new DangKyBienSoanGiaoTrinh(data[1], tgs, data[2], data[3]);
            a.setTienDo(Integer.parseInt(data[data.length - 1]));
            a.setMaGT(data[0]);
            dkbss.add(a);
        }
       
        fileController.CloseFileAfterRead();
        return dkbss;
    }

    private void WriteFileTĐ(List<DangKyBienSoanGiaoTrinh> dkbss, String fileName) {
        FileController fileController = new FileController();
        fileController.OpenFileToWrite(fileName, false);
        for (DangKyBienSoanGiaoTrinh dkb : dkbss) {
            String str = "";
            str += dkb.getMaGT() + "|" + dkb.getTenGT() + "|" + dkb.getNoiDung() + "|" + dkb.getThoiGianHT() + "|" + dkb.getThoiGianDK() + "|";
            for (TacGia tacGia : dkb.getTacGias()) {
                String tmp = "*" + tacGia.getTenTacGia() + "*" + tacGia.getVaiTro();
                str += tmp;
            }
            str += "|" + dkb.getTienDo();
            fileController.getPrintWriter().println(str);
        }
        fileController.CloseFileAfterWrite();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XinGiaHanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XinGiaHanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XinGiaHanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XinGiaHanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XinGiaHanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HuyBaoCao;
    private javax.swing.JButton XinGiaHan;
    private javax.swing.JPanel formBaoCaoTienDo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtGiaHan;
    private javax.swing.JTextField txtMaGT;
    // End of variables declaration//GEN-END:variables
}
